image: Visual Studio 2019

version: 4.0.{build}

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
configuration: Debug

install:
  - cmd: choco install dotnetcore-sdk --pre
  
before_build:
  - cmd.exe /c externalDlls\libnodave\vcwinmake_64.bat
  - cmd.exe /c externalDlls\libnodave\vcwinmake.bat
  - externalDlls\copydlls.bat
  - nuget restore
  
build:
  project: DotNetSiemensPLCToolBoxLibrary.sln

after_build:
  - 7z a TiaGitHandler.zip %APPVEYOR_BUILD_FOLDER%\TiaGitHandler\bin\Debug\net461\*.*
  - 7z a WPFVarTab.zip %APPVEYOR_BUILD_FOLDER%\WPFVarTab\bin\Debug\net462\*.*
  - 7z a Protokoller.zip %APPVEYOR_BUILD_FOLDER%\DotNetDatenbankProtokollerV2\DotNetSimaticDatabaseProtokollerService\bin\Debug\net462\*.*
  - 7z a S7ToolBox.zip %APPVEYOR_BUILD_FOLDER%\TestProjectFileFunctions\bin\Debug\net461\*.*

artifacts:
  - path: externalDlls\libnodave\libnodave_jfkmod.dll
    name: libnodave_jfkmod.dll
  - path: externalDlls\libnodave\libnodave_jfkmod64.dll
    name: libnodave_jfkmod64.dll
  - path: '**\DotNetSiemensPLCToolBoxLibrary*.nupkg' 
  - path: TiaGitHandler.zip
    name: TiaGitHandler
  - path: S7ToolBox.zip
    name: S7ToolBox
  - path: WPFVarTab.zip
    name: WPFVarTab
  - path: Protokoller.zip
    name: Protokoller
    
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  
